var flower = [
  {
    name:"联系方式",
    phone:"<a href='tel:13892739412'>电话联系</a>",
    pic:"./img/flower/lxfs.jpg",
    address:"扶风县法门镇宝塔村旁慈慧路东侧",
    wechat:"chj628821",
    fname:"lxfs.jpg"
  },
  {
    name:"B001.jpg-new",
    code:"B001",
    price:"--",
    pic:"./img/flower/B001.jpg",
    remark:"--",
    fname:"B001.jpg"
  },
  {
    name:"B002.jpg-new",
    code:"B002",
    price:"--",
    pic:"./img/flower/B002.jpg",
    remark:"--",
    fname:"B002.jpg"
  },
  {
    name:"B003.jpg-new",
    code:"B003",
    price:"--",
    pic:"./img/flower/B003.jpg",
    remark:"--",
    fname:"B003.jpg"
  },
  {
    name:"B004.jpg-new",
    code:"B004",
    price:"--",
    pic:"./img/flower/B004.jpg",
    remark:"--",
    fname:"B004.jpg"
  },
  {
    name:"B005.jpg-new",
    code:"B005",
    price:"--",
    pic:"./img/flower/B005.jpg",
    remark:"--",
    fname:"B005.jpg"
  },
  {
    name:"B006.jpg-new",
    code:"B006",
    price:"--",
    pic:"./img/flower/B006.jpg",
    remark:"--",
    fname:"B006.jpg"
  },
  {
    name:"B007-1.jpg-new",
    code:"B007-1",
    price:"--",
    pic:"./img/flower/B007-1.jpg",
    remark:"--",
    fname:"B007-1.jpg"
  },
  {
    name:"B007-2.jpg-new",
    code:"B007-2",
    price:"--",
    pic:"./img/flower/B007-2.jpg",
    remark:"--",
    fname:"B007-2.jpg"
  },
  {
    name:"B008.jpg-new",
    code:"B008",
    price:"--",
    pic:"./img/flower/B008.jpg",
    remark:"--",
    fname:"B008.jpg"
  },
  {
    name:"B009.jpg-new",
    code:"B009",
    price:"--",
    pic:"./img/flower/B009.jpg",
    remark:"--",
    fname:"B009.jpg"
  },
  {
    name:"B010.jpg-new",
    code:"B010",
    price:"--",
    pic:"./img/flower/B010.jpg",
    remark:"--",
    fname:"B010.jpg"
  },
  {
    name:"B011.jpg-new",
    code:"B011",
    price:"--",
    pic:"./img/flower/B011.jpg",
    remark:"--",
    fname:"B011.jpg"
  },,,,
]
