var manualflower = [
  {
    name:"联系方式",
    phone:"<a href='tel:13892739412'>电话联系</a>",
    pic:"./img/manualflower/lxfs.jpg",
    address:"扶风县法门镇宝塔村旁慈慧路东侧",
    wechat:"chj628821",
    fname:"lxfs.jpg"
  },
  {
    name:"A001.jpg-new",
    code:"A001",
    price:"--",
    pic:"./img/manualflower/A001.jpg",
    remark:"描述",
    fname:"A001.jpg"
  },
  {
    name:"A002.jpg-new",
    code:"A002",
    price:"--",
    pic:"./img/manualflower/A002.jpg",
    remark:"描述",
    fname:"A002.jpg"
  },
  {
    name:"A003.jpg-new",
    code:"A003",
    price:"--",
    pic:"./img/manualflower/A003.jpg",
    remark:"描述",
    fname:"A003.jpg"
  },
  {
    name:"A004.jpg-new",
    code:"A004",
    price:"--",
    pic:"./img/manualflower/A004.jpg",
    remark:"描述",
    fname:"A004.jpg"
  },
  {
    name:"A005.jpg-new",
    code:"A005",
    price:"--",
    pic:"./img/manualflower/A005.jpg",
    remark:"描述",
    fname:"A005.jpg"
  },
  {
    name:"A006.jpg-new",
    code:"A006",
    price:"--",
    pic:"./img/manualflower/A006.jpg",
    remark:"描述",
    fname:"A006.jpg"
  },
  {
    name:"A007.jpg-new",
    code:"A007",
    price:"--",
    pic:"./img/manualflower/A007.jpg",
    remark:"描述",
    fname:"A007.jpg"
  },
  {
    name:"A008.jpg-new",
    code:"A008",
    price:"--",
    pic:"./img/manualflower/A008.jpg",
    remark:"描述",
    fname:"A008.jpg"
  },
  {
    name:"A009.jpg-new",
    code:"A009",
    price:"--",
    pic:"./img/manualflower/A009.jpg",
    remark:"描述",
    fname:"A009.jpg"
  },
  {
    name:"A010.jpg-new",
    code:"A010",
    price:"--",
    pic:"./img/manualflower/A010.jpg",
    remark:"描述",
    fname:"A010.jpg"
  },
  {
    name:"A011.jpg-new",
    code:"A011",
    price:"--",
    pic:"./img/manualflower/A011.jpg",
    remark:"描述",
    fname:"A011.jpg"
  },
  {
    name:"A012.jpg-new",
    code:"A012",
    price:"--",
    pic:"./img/manualflower/A012.jpg",
    remark:"描述",
    fname:"A012.jpg"
  },
  {
    name:"A013.jpg-new",
    code:"A013",
    price:"--",
    pic:"./img/manualflower/A013.jpg",
    remark:"描述",
    fname:"A013.jpg"
  },
  {
    name:"A014.jpg-new",
    code:"A014",
    price:"--",
    pic:"./img/manualflower/A014.jpg",
    remark:"描述",
    fname:"A014.jpg"
  },
  {
    name:"A015.jpg-new",
    code:"A015",
    price:"--",
    pic:"./img/manualflower/A015.jpg",
    remark:"描述",
    fname:"A015.jpg"
  },
  {
    name:"A016.jpg-new",
    code:"A016",
    price:"--",
    pic:"./img/manualflower/A016.jpg",
    remark:"描述",
    fname:"A016.jpg"
  }
]
