var other = [
  {
    name:"联系方式",
    phone:"<a href='tel:13892739412'>电话联系</a>",
    pic:"./img/other/lxfs.jpg",
    address:"扶风县法门镇宝塔村旁慈慧路东侧",
    wechat:"chj628821",
    fname:"lxfs.jpg"
  },
  {
    name:"长钱纸（手工）",
    code:"D001",
    price:"--",
    pic:"./img/other/D001.jpg",
    remark:"",
    fname:"D001.jpg"
  },
  {
    name:"别墅",
    code:"D002",
    price:"--",
    pic:"./img/other/D002.jpg",
    remark:"描述",
    fname:"D002.jpg"
  },
  {
    name:"金银山",
    code:"D003",
    price:"--",
    pic:"./img/other/D003.jpg",
    remark:"描述",
    fname:"D003.jpg"
  },
  {
    name:"斗子",
    code:"D004",
    price:"--",
    pic:"./img/other/D004.jpg",
    remark:"描述",
    fname:"D004.jpg"
  },
  {
    name:"金银摇钱树（纸）",
    code:"D005",
    price:"--",
    pic:"./img/other/D005.jpg",
    remark:"描述",
    fname:"D005.jpg"
  },
  {
    name:"蜡烛",
    code:"D006",
    price:"--",
    pic:"./img/other/D006.jpg",
    remark:"描述",
    fname:"D006.jpg"
  },
  {
    name:"金摇元宝",
    code:"D007",
    price:"--",
    pic:"./img/other/D007.jpg",
    remark:"描述",
    fname:"D007.jpg"
  },
  {
    name:"汽车（纸）",
    code:"D008",
    price:"--",
    pic:"./img/other/D008.jpg",
    remark:"描述",
    fname:"D008.jpg"
  },
  {
    name:"电视（纸）",
    code:"D009",
    price:"--",
    pic:"./img/other/D009.jpg",
    remark:"描述",
    fname:"D009.jpg"
  },
  {
    name:"洗衣机（纸）",
    code:"D010",
    price:"--",
    pic:"./img/other/D010.jpg",
    remark:"描述",
    fname:"D010.jpg"
  },
  {
    name:"长钱纸（成品）",
    code:"D011",
    price:"--",
    pic:"./img/other/D011.jpg",
    remark:"描述",
    fname:"D011.jpg"
  },
  {
    name:"D012.jpg-new",
    code:"D012",
    price:"--",
    pic:"./img/other/D012.jpg",
    remark:"描述",
    fname:"D012.jpg"
  },
  {
    name:"D013.jpg-new",
    code:"D013",
    price:"--",
    pic:"./img/other/D013.jpg",
    remark:"塑料",
    fname:"D013.jpg"
  },
  {
    name:"七彩灯",
    code:"D014",
    price:"--",
    pic:"./img/other/D014.jpg",
    remark:"七彩灯-塑料",
    fname:"D014.jpg"
  },
  {
    name:"吉祥灯",
    code:"D015",
    price:"--",
    pic:"./img/other/D015.jpg",
    remark:"吉祥灯",
    fname:"D015.jpg"
  },
  {
    name:"桶纸",
    code:"D016",
    price:"--",
    pic:"./img/other/D016.jpg",
    remark:"桶纸",
    fname:"D016.jpg"
  }
]
