var parts = [
  {
    name:"联系方式",
    phone:"<a href='tel:13892739412'>电话联系</a>",
    pic:"./img/parts/lxfs.jpg",
    address:"扶风县法门镇宝塔村旁慈慧路东侧",
    wechat:"chj628821",
    fname:"lxfs.jpg"
  },
  {
    name:"食饹",
    code:"C000",
    price:"--",
    pic:"./img/parts/C000.jpg",
    remark:"--",
    fname:"C000.jpg"
  },
  {
    name:"献祭-水果造型",
    code:"C001",
    price:"--",
    pic:"./img/parts/C001.jpg",
    remark:"带食物造型",
    fname:"C001.jpg"
  },
  {
    name:"献祭",
    code:"C002",
    price:"--",
    pic:"./img/parts/C002.jpg",
    remark:"花纹",
    fname:"C002.jpg"
  },
  {
    name:"水饭",
    code:"C003",
    price:"--",
    pic:"./img/parts/C003.jpg",
    remark:"--",
    fname:"C003.jpg"
  },,
  {
    name:"献祭",
    code:"C004",
    price:"--",
    pic:"./img/parts/C004.jpg",
    remark:"无造型",
    fname:"C004.jpg"
  },,,
]
